obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_UBNT_HDD_PWRCTL) += ubnt-hdd-pwrctl.o
obj-$(CONFIG_UBNT_HDD_PWRCTL_V2) += ubnt-hdd-pwrctl-v2.o
obj-y         += poe/
